### ISSUE TITLE
bug mision sede clase

### ISSUE THREAD

**Issue by HardAzkeel** [holydeew/WoWHellgarve-Legion#170] opened 2023-04-13 01:28 UTC
the mission of frustrated destiny does not appear and I go to the instance and nothing to complete it, so it is not a quest.
https://www.wowhead.com/es/quest=44481/destino-frustrado

**Comment by skeezerbean** [comment] 2024-08-30 19:10
Duplicate of https://github.com/holydeew/WoWHellgarve-Legion/issues/208

**Closed as completed by skeezerbean** 2024-08-30 19:10 UTC
