### ISSUE TITLE
[RAID] Antoran High Command Boss crashing the server

### ISSUE THREAD

**Issue by Muertador** [holydeew/WoWHellgarve-Legion#279] opened 2023-07-09 17:44 UTC
Whenever attacking the 3rd boss of Antorus, Antoran High Command, on LFR/Normal/Heroic difficulty, the server crashes, I can beat it fine on mythic

**Comment by Muertador** [comment] 2023-07-10 16:51
EDIT: Seems to only be a problem with my Hunter Cazzador, happens even on mythic now

**Comment by skeezerbean** [comment] 2024-01-19 02:08
Do you have any other details on this, such as what specifically seemed to crash?

**Comment by skeezerbean** [comment] 2024-06-18 22:10
No other details given, cannot reproduce. Closing.

**Closed as completed by skeezerbean** 2024-06-18 22:10 UTC
