### ISSUE TITLE
Black rook hold Greater power : warrior quest

### ISSUE THREAD

**Issue by PokeUrEyeOut** [holydeew/WoWHellgarve-Legion#262] opened 2023-06-23 14:20 UTC
After 16 runs the item has yet to drop from final boss. Greater Demonic runestone. 
Character name Kapn. 
I have tried normal and heroic everyday since picking up this quest for the warrior class hall questline.
https://www.wowhead.com/quest=43506/black-rook-hold-greater-power

**Comment by skeezerbean** [comment] 2023-12-29 00:59
Duplicate of https://github.com/holydeew/WoWHellgarve-Legion/issues/175
Fix has been sent in, not sure when it will be applied

**Closed as completed by skeezerbean** 2023-12-29 00:59 UTC
