### ISSUE TITLE
[Quest] [Legion] [Dungeon] Black Rook Hold: Greater Power

### ISSUE THREAD

**Issue by justSelim** [holydeew/WoWHellgarve-Legion#346] opened 2023-08-09 15:04 UTC
Quest ID: [Black Rook Hold: Greater Power 43506](https://www.wowhead.com/quest=43506/black-rook-hold-greater-power)
NPC: [Latosius 98970](https://www.wowhead.com/npc=98970/latosius) , [Dantalionax 99611](https://www.wowhead.com/de/npc=99611/dantalionax)
Item ID: [Greater Demonic Runestone 139453](https://www.wowhead.com/item=139453/greater-demonic-runestone)

Current Behaviour: Killing [Latosius 98970](https://www.wowhead.com/npc=98970/latosius) or his demonic form [Dantalionax 99611](https://www.wowhead.com/de/npc=99611/dantalionax) is not dropping Item  [Greater Demonic Runestone 139453](https://www.wowhead.com/item=139453/greater-demonic-runestone)

Expected Behaviour: Killing [Latosius 98970](https://www.wowhead.com/npc=98970/latosius) or his demonic form [Dantalionax 99611](https://www.wowhead.com/de/npc=99611/dantalionax) should drop Item  [Greater Demonic Runestone 139453](https://www.wowhead.com/item=139453/greater-demonic-runestone)

Video: [Youtube](https://www.youtube.com/watch?v=Ax24Q7r8vPE)

**Comment by skeezerbean** [comment] 2023-12-29 00:59
Duplicate of https://github.com/holydeew/WoWHellgarve-Legion/issues/175
Fix has been sent in, not sure when it will be applied

**Closed as completed by skeezerbean** 2023-12-29 00:59 UTC
