### ISSUE TITLE
Bug mision de suramar

### ISSUE THREAD

**Issue by HardAzkeel** [holydeew/WoWHellgarve-Legion#171] opened 2023-04-15 08:21 UTC
the mission "or against us" the npc when he speaks does not appear the dialogue to complete the mission. and thus continue the chain of suramar missions.

https://www.wowhead.com/es/quest=43311/o-contra-nosotros

**Comment by skeezerbean** [comment] 2024-08-30 19:04
Duplicate of https://github.com/holydeew/WoWHellgarve-Legion/issues/155

**Closed as completed by skeezerbean** 2024-08-30 19:04 UTC
